# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4adbcf838dc68b6a6e72c5a7c9d2ef3b196c9da4ce466ca0d1e380029b4eb03facd9014335ee9539267c99bd56544e321cb49d6f36dbad1c697535927ffeb8

test:
  secret_key_base: e891086dc6e7a858636f648822d56baa1b54935b2f6fd4d7b32906e849756866cf0195d9df970cc13377a2a3a894ca15294d7b8687fce16fc92e99ea6998cd2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
